site_name: THUASTA Tech Roadmap

nav:
  - Home: index.md
  - Comp Dept.:
    - Roadmap: comp_dept/roadmap.md
    - Syllabus: comp_dept/syllabus.md
  - Topics:
    - CI/CD:
      - topics/ci_cd/index.md
      - GitHub Actions: topics/ci_cd/github_actions.md
    - Containerization:
      - topics/container/index.md
      - Docker: topics/container/docker.md
    - Internet:
      - topics/networking/index.md
      - How does the Internet work?: topics/networking/internet.md
      - What is HTTP?: topics/networking/http.md
      - WebSockets: topics/networking/websockets.md
    - Learn a Language:
      - topics/prog_lang/index.md
      - C#: topics/prog_lang/csharp.md
      - Python: topics/prog_lang/python.md
    - Markdown: topics/markdown.md
    - OS and General Knowledge:
      - topics/os/index.md
      - Terminal Usage: topics/os/terminal.md
      - Basic Terminal Commands: topics/os/commands.md
    - Repo Hosting Service:
      - topics/repo/index.md
      - GitHub: topics/repo/github.md
    - Testing:
      - topics/testing/index.md
      - Unit Testing: topics/testing/unit_testing.md
      - Integration Testing: topics/testing/int_testing.md
    - Version Control System:
      - topics/vcs/index.md
      - Git: topics/vcs/git.md
    - Visual Studio Code: topics/vscode.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
